routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\TestsController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::middleware(['auth'])->group(function(){
    Route::get("/", function(){
        return redirect(route("users.index"));
    });


    Route::get('/home', [\App\Http\Controllers\HomeController::class, "index"])->name('home');

    Route::resource('users', \App\Http\Controllers\UsersController::class);

    Route::get('tests/test',[TestsController::class, "test"])->name("tests.test");

    Route::post('tests/test/random/create',[TestsController::class, 'createRandomTest'])->name("tests.create.random");
    Route::post('tests/test/hosted/create',[TestsController::class, 'createHostedTest'])->name("tests.create.hosted");


    Route::post('tests/test/submit', [TestsController::class, 'submit'])->name("tests.submit");
    Route::post('tests/test/cancel', [TestsController::class, 'cancel'])->name("tests.cancel");

    Route::post('tests/test/question', [TestsController::class, 'getQuestion']);

    Route::get('tests/get/test/{subject_id}',[TestsController::class, 'getTests'])->name('tests.getTests');
    Route::get('tests/get/question/{subject_id}', [TestsController::class, 'getQuestions'])->name('tests.getQuestions');
    Route::get('tests/get/marks/{subject_id}',[TestsController::class, 'getMarks'])->name('tests.getMarks');
});
Route::get("questions/generatedQuestions",function(){
return view('questions.generatedQuestions');
});
Route::post('tests/hosted/test', [TestsController::class,"getHostedTest"])->name("tests.hosted")->middleware(['auth', 'blockuser']);
Route::get('tests/previous',[TestsController::class, 'previous'])->name('tests.previous')->middleware(['auth', 'blockhost']);
Route::post('tests/{test}/view',[TestsController::class, 'view'])->name('tests.view')->middleware(['auth', 'blockhost']);
Route::get('tests/random',[TestsController::class, 'random'])->name("tests.random")->middleware(['auth', 'blockhost']);

Route::resource('questions',\App\Http\Controllers\QuestionsController::class)->middleware(['auth', 'blockuser']);
Route::get("subjects", [\App\Http\Controllers\SubjectsController::class, "index"])->name("subjects.index")->middleware(['auth', 'admin']);
Route::get("subjects/create", [\App\Http\Controllers\SubjectsController::class, "create"])->name("subjects.create")->middleware(['auth', 'blockuser']);
Route::post("subjects", [\App\Http\Controllers\SubjectsController::class, "store"])->name("subjects.store")->middleware(['auth', 'blockuser']);
Route::put("subjects/{subject}", [\App\Http\Controllers\SubjectsController::class, "update"])->name("subjects.update")->middleware(['auth', 'admin']);
Route::delete("subjects/{subject}", [\App\Http\Controllers\SubjectsController::class, "destroy"])->name("subjects.destroy")->middleware(['auth', 'admin']);

Route::get("modules", [\App\Http\Controllers\ModulesController::class, "index"])->name("modules.index")->middleware(['auth', 'admin']);
Route::get("modules/create", [\App\Http\Controllers\ModulesController::class, "create"])->name("modules.create")->middleware(['auth', 'blockuser']);
Route::post("modules", [\App\Http\Controllers\ModulesController::class, "store"])->name("modules.store")->middleware(['auth', 'blockuser']);
Route::put("modules/{module}", [\App\Http\Controllers\ModulesController::class, "update"])->name("modules.update")->middleware(['auth', 'admin']);
Route::delete("modules/{module}", [\App\Http\Controllers\ModulesController::class, "destroy"])->name("modules.destroy")->middleware(['auth', 'admin']);

Route::resource('tests',TestsController::class)->middleware(['test', 'auth']);

// Route::get("questions/generatedQuestions", function(){
//     
// });

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\DB;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','address'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function tests(){
        return $this->belongsToMany(Test::class)->withTimestamps();
    }

    public function createdTests(){
        return $this->hasMany(Test::class, "user_id");
    }

    public function createdQuestions(){
        return $this->hasMany(Question::class, "user_id");
    }

    public function getTestAverageBySubject($subject_id){
        $user = auth()->user();
        $subject = Subject::find($subject_id);
        $testCount = 0;
        $totalMarks = 0;
        $obtainedMarks = 0;
        foreach($this->tests as $test){
            // dd($test->module->subject_id);
            if($test->modules()->first()->subject_id == $subject->id){
                $testCount++;
                $totalMarks += intval($test->total_marks, 10);
                $test_user = DB::table('test_user')->where('test_id',$test->id)->where('user_id',$user->id)->first();
                $obtainedMarks += intval($test_user->marks_obtained, 10);
            }
        }
        $averagePercentage = $totalMarks == 0 ? 0 : intval(($obtainedMarks/$totalMarks) * 100, 10);
        return $averagePercentage;
    }
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\UserEditRequest;
use App\Subject;
use App\User;
use Illuminate\Http\Request;

class UsersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if(auth()->user()->role == "admin"){
            $users = User::paginate(10);
            $user = auth()->user();
            $tests = $user->createdTests;
            if($tests == null){
                $testsCount = 0;
            }else{
                $testsCount = count($tests->toArray());
            }
            $questions = $user->createdQuestions;
            if($questions == null){
                $questionsCount = 0;
            }else{
                $questionsCount = count($questions->toArray());
            }
            $usersCount = 0;
            foreach($tests as $test){
                $usersCount += count($test->users);
            }
            return view('users.index',compact([
                'testsCount',
                'usersCount',
                'questionsCount',
                'users'
            ]));
        }else if(auth()->user()->role == "host"){
            $user = auth()->user();
            $tests = $user->createdTests;
            if($tests == null){
                $testsCount = 0;
            }else{
                $testsCount = count($tests->toArray());
            }
            $questions = $user->createdQuestions;
            if($questions == null){
                $questionsCount = 0;
            }else{
                $questionsCount = count($questions->toArray());
            }
            $usersCount = 0;
            foreach($tests as $test){
                $usersCount += count($test->users);
            }
            return view('users.index',compact([
                'testsCount',
                'usersCount',
                'questionsCount'
            ]));
        }else{

            $subjectsWithAverageMarks = [];
            $subjects = Subject::all();
            foreach($subjects as $subject){
                $subjectsWithAverageMarks[$subject->name] = auth()->user()->getTestAverageBySubject($subject->id);
            }

            $user = auth()->user();
            $tests = $user->tests;
            $testsCount = count($tests->toArray());
            return view('users.index',compact([
                'testsCount',
                'subjectsWithAverageMarks',
            ]));
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        return view('users.show', compact(["user"]));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        return view('users.edit', compact(["user"]));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(UserEditRequest $request, User $user)
    {
        // dd($user);
        $request->validated();
        $user->update([
            "name" => $request->name,
            "email" => $request->email,
            "phone" => $request->phone,
            "address" => $request->address,
        ]);

        return redirect(route("users.show", auth()->user()->id));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        //
    }
}

resources/views/users/edit.blade.php
@extends('layouts.app')

@section('page-title')
Edit Student
@endsection

@section('content')

<div class="card shadow">
    <div class="card-header">
        <div class="d-flex justify-content-between">
            <div class="">
                <p>Student</p>
            </div>
        </div>
    </div>
    <div class="card-body">
        <form action="{{route('users.update', $user->id)}}" method="post">
            @csrf
            @method("PUT")
            <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label for="name">Name</label>
                    <input type="text" id="name" name="name" placeholder="Enter Name" value="{{ old('name', $user->name) }}" class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}">
                    @error('name')
                        <div class="text-danger">{{ $message }}</div>
                    @enderror
                </div>
            </div>

            <div class="col-md-6">
                <div class="form-group">
                    <label for="exampleInputEmail1">Email address</label>
                    <input type="text" id="email" name="email" placeholder="Enter Email" value="{{ old('email', $user->email) }}" class="form-control {{ $errors->has('email') ? 'is-invalid' : '' }}">
                    @error('email')
                        <div class="text-danger">{{ $message }}</div>
                    @enderror
                </div>
            </div>

            <div class="col-md-6">
                <div class="form-group">
                    <label for="phone">Phone Number</label>
                    <input type="text" id="name" name="phone" placeholder="Enter Name" value="{{ old('phone', $user->phone) }}" class="form-control {{ $errors->has('phone') ? 'is-invalid' : '' }}">
                    @error('phone')
                        <div class="text-danger">{{ $message }}</div>
                    @enderror
                </div>
            </div>

            <div class="col-md-6">
                <div class="form-group">
                    <label for="address">Address</label>
                    <input type="text" id="name" name="address" placeholder="Enter Address" value="{{ old('address', $user->address) }}" class="form-control {{ $errors->has('address') ? 'is-invalid' : '' }}">
                    @error('address')
                        <div class="text-danger">{{ $message }}</div>
                    @enderror
                </div>
            </div>

            <div class="col-md-12 text-center mt-2 d-flex justify-content-end">
                <button type="submit" class="btn btn-outline-primary">Save</button>
            </div>
        </div>
        </form>
    </div>
</div>

@endsection

resources/views/users/index.blade.php
@extends('layouts.app') @section('content')
<!-- For User -->

@canany(['adminOption','hostOption'], \App\User::class)
<div class="row mt-5">
    <div class="col-md-4 d-flex justify-content-center">
        <div class="card shadow" style="width: 18rem;">
            <div class="card-body">
                <div class="d-flex justify-content-between">
                    <h3 class="card-text">{{$testsCount}}</h3>
                    <i class="fa fa-book fa-3x text-yellow"></i>
                </div>
                <h6 class="card-title mb-1">Created Tests</h6>
            </div>
        </div>
    </div>

    <div class="col-md-4 d-flex justify-content-center">
        <div class="card shadow" style="width: 18rem;">
            <div class="card-body">
                <div class="d-flex justify-content-between">
                    <h3 class="card-text">{{$usersCount}}</h3>
                    <i class="fa fa-user fa-3x text-yellow"></i>
                </div>
                <h6 class="card-title mb-1">Users</h6>
            </div>
        </div>
    </div>

    <div class="col-md-4 d-flex justify-content-center">
        <div class="card shadow" style="width: 18rem;">
            <div class="card-body">
                <div class="d-flex justify-content-between">
                    <h3 class="card-text">{{$questionsCount}}</h3>
                    <i class="fa fa-pen fa-3x text-yellow"></i>
                </div>
                <h6 class="card-title mb-1">Created Questions</h6>
            </div>
        </div>
    </div>
</div>
@endcanany

<!-- For Admin -->
@can('adminOption', \App\User::class)
<div class="card shadow mt-5">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Users</h6>
    </div>
    <div class="card-body">
        <div class="">
            <table class="table table-bordered">
                <thead class="">
                    <tr>
                        <th scope="col">Name</th>
                        <th scope="col">Email</th>
                        <th scope="col">Phone Number</th>
                        <th scope="col">Address</th>
                        <th scope="col">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($users as $user)
                    <tr>
                        <td>{{ $user->name }}</td>
                        <td>{{ $user->email }}</td>
                        <td>{{ $user->phone }}</td>
                        <td>{{ $user->address }}</td>
                        <td>
                            <div class="">
                                <a
                                    href="{{ route('users.show',$user->id) }}"
                                    class="btn btn-outline-secondary mr-1">View</a>
                            </div>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
    <div class="card-footer d-flex justify-content-center">
        {{ $users->links() }}
    </div>
</div>

@endcan @can('userOption', \App\User::class)
<div class="container">
<div class="row mt-5">
    <div class="col-md-12">
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Overall Standings</h6>
            </div>
            <div class="card-body">
                <div class="chart-bar">
                    <div class="chartjs-size-monitor">
                        <div class="chartjs-size-monitor-expand">
                            <div class=""></div>
                        </div>
                        <div class="chartjs-size-monitor-shrink">
                            <div class=""></div>
                        </div>
                    </div>
                    <canvas
                        id="myBarChart"
                        width="668"
                        height="320"
                        class="chartjs-render-monitor"
                        style="display: block; width: 668px; height: 320px;"></canvas>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
@endcan @endsection @section("page-level-scripts")
@can('userOption', \App\User::class)
<script src="{{ asset('js/vendor/chart.js/Chart.js')}}"></script>
<script>
    var data = {!! json_encode($subjectsWithAverageMarks) !!};
</script>
<script src="{{ asset('js/charts.js')}}"></script>
@endcan
@endsection

resources/views/users/show.blade.php
@extends('layouts.app')

@section('page-title')
View Student
@endsection

@section('content')

<div class="card shadow">
    <div class="card-header">
        <div class="d-flex justify-content-between">
            <div class="">
                <p>Student</p>
            </div>
        </div>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label for="name">Name</label>
                    <input type="text" class="form-control" id="name" placeholder="Enter Name" value="{{ $user->name }}" disabled>
                </div>
            </div>

            <div class="col-md-6">
                <div class="form-group">
                    <label for="exampleInputEmail1">Email address</label>
                    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email" value="{{ $user->email }}" disabled>
                    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
                </div>
            </div>

            <div class="col-md-6">
                <div class="form-group">
                    <label for="phone">Phone Number</label>
                    <input type="text" class="form-control" id="phone" placeholder="Enter Phone" value="{{ $user->phone }}" disabled>
                </div>
            </div>

            <div class="col-md-6">
                <div class="form-group">
                    <label for="address">Address</label>
                    <input type="text" class="form-control" id="address" placeholder="Enter Address" value="{{ $user->address }}" disabled>
                </div>
            </div>

        </div>
    </div>
</div>

@endsection