routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\TestsController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::middleware(['auth'])->group(function(){
    Route::get("/", function(){
        return redirect(route("users.index"));
    });


    Route::get('/home', [\App\Http\Controllers\HomeController::class, "index"])->name('home');

    Route::resource('users', \App\Http\Controllers\UsersController::class);

    Route::get('tests/test',[TestsController::class, "test"])->name("tests.test");

    Route::post('tests/test/random/create',[TestsController::class, 'createRandomTest'])->name("tests.create.random");
    Route::post('tests/test/hosted/create',[TestsController::class, 'createHostedTest'])->name("tests.create.hosted");


    Route::post('tests/test/submit', [TestsController::class, 'submit'])->name("tests.submit");
    Route::post('tests/test/cancel', [TestsController::class, 'cancel'])->name("tests.cancel");

    Route::post('tests/test/question', [TestsController::class, 'getQuestion']);

    Route::get('tests/get/test/{subject_id}',[TestsController::class, 'getTests'])->name('tests.getTests');
    Route::get('tests/get/question/{subject_id}', [TestsController::class, 'getQuestions'])->name('tests.getQuestions');
    Route::get('tests/get/marks/{subject_id}',[TestsController::class, 'getMarks'])->name('tests.getMarks');
});
Route::get("questions/generatedQuestions",function(){
return view('questions.generatedQuestions');
});
Route::post('tests/hosted/test', [TestsController::class,"getHostedTest"])->name("tests.hosted")->middleware(['auth', 'blockuser']);
Route::get('tests/previous',[TestsController::class, 'previous'])->name('tests.previous')->middleware(['auth', 'blockhost']);
Route::post('tests/{test}/view',[TestsController::class, 'view'])->name('tests.view')->middleware(['auth', 'blockhost']);
Route::get('tests/random',[TestsController::class, 'random'])->name("tests.random")->middleware(['auth', 'blockhost']);

Route::resource('questions',\App\Http\Controllers\QuestionsController::class)->middleware(['auth', 'blockuser']);
Route::get("subjects", [\App\Http\Controllers\SubjectsController::class, "index"])->name("subjects.index")->middleware(['auth', 'admin']);
Route::get("subjects/create", [\App\Http\Controllers\SubjectsController::class, "create"])->name("subjects.create")->middleware(['auth', 'blockuser']);
Route::post("subjects", [\App\Http\Controllers\SubjectsController::class, "store"])->name("subjects.store")->middleware(['auth', 'blockuser']);
Route::put("subjects/{subject}", [\App\Http\Controllers\SubjectsController::class, "update"])->name("subjects.update")->middleware(['auth', 'admin']);
Route::delete("subjects/{subject}", [\App\Http\Controllers\SubjectsController::class, "destroy"])->name("subjects.destroy")->middleware(['auth', 'admin']);

Route::get("modules", [\App\Http\Controllers\ModulesController::class, "index"])->name("modules.index")->middleware(['auth', 'admin']);
Route::get("modules/create", [\App\Http\Controllers\ModulesController::class, "create"])->name("modules.create")->middleware(['auth', 'blockuser']);
Route::post("modules", [\App\Http\Controllers\ModulesController::class, "store"])->name("modules.store")->middleware(['auth', 'blockuser']);
Route::put("modules/{module}", [\App\Http\Controllers\ModulesController::class, "update"])->name("modules.update")->middleware(['auth', 'admin']);
Route::delete("modules/{module}", [\App\Http\Controllers\ModulesController::class, "destroy"])->name("modules.destroy")->middleware(['auth', 'admin']);

Route::resource('tests',TestsController::class)->middleware(['test', 'auth']);

// Route::get("questions/generatedQuestions", function(){
//     
// });

app/Question.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;
use PhpParser\Node\Expr\AssignOp\Mod;

class Question extends Model
{
    protected $fillable = ["id",  'statement', 'module_id', "user_id"];
    public function options(){
        return $this->hasMany(Option::class);
    }

    public function subject(){
        return $this->belongsTo(Subject::class);
    }
    public function module(){
        return $this->belongsTo(Module::class);
    }

    public function tests(){
        return $this->belongsToMany(Test::class)->withTimestamps();
    }

    public function owner(){
        return $this->belongsTo(User::class,"user_id");
    }

    public function getCheckedOption($test_user_id, $option_id){
        $option = DB::table("question_test_user")->where("question_id",$this->id)->where("test_user_id", $test_user_id)->first();
        if(!$option){
            return ' ';
        }else if($option->option_id === $option_id){
            return 'checked';
        }
    }

    public function isAnswerSelected($test_user_id){
        $question = DB::table("question_test_user")->where("question_id",$this->id)->where("test_user_id", $test_user_id)->first();
        return $question->option_id != null;
    }

    public function getCorrectOption(){
        foreach($this->options as $option){
            if($option->is_correct == "1"){
                return $option;
            }
        }
    }
}

app/Http/Controllers/QuestionsController.php
<?php

namespace App\Http\Controllers;

use App\Module;
use App\Option;
use App\Question;
use App\Subject;
use Illuminate\Http\Request;

class QuestionsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $modules = Module::all();
        return view('questions.create', compact(['modules']));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // dd($request);
    //    dd(((count($request->toArray())-2)/3));
        // $request = json_encode();
        // $data = json_decode($request->questions, true);
        // var_dump($data);
        for ($i = 0; $i < ((count($request->toArray())-2)/3); $i++){
            $question = Question::create([
                'statement' => request("question_" . $i),
                'module_id' => $request->module_id,
                'user_id' => auth()->user()->id,
            ]);
            for($j=0; $j<count(request("q".$i)); $j++){
                Option::create([
                    'statement' => request("q".$i)[$j],
                    'question_id' => $question->id,
                    'is_correct' => request("q-".$i."-a") == $j+1,
                ]);
            }
            
        } 


        // echo "success";
        session()->flash("success", "Questions were added successfully");
        return redirect(route('users.index'));
    }

    public function getQuestion($row)
    {
        return $row[0];
    }

    public function getOptions($row)
    {
        return $row[1][0];
    }

    public function getCorrectOption($row)
    {
        return $row[1][1];
    }

    public function getModule($row)
    {
        return $row[2];
    }
    /**
     * Display the specified resource.
     *
     * @param  \App\Question  $question
     * @return \Illuminate\Http\Response
     */
    public function show(Question $question)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Question  $question
     * @return \Illuminate\Http\Response
     */
    public function edit(Question $question)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Question  $question
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Question $question)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Question  $question
     * @return \Illuminate\Http\Response
     */
    public function destroy(Question $question)
    {
        //
    }

    public function generatedQuestions(Request $request){
        dd($request);
    }

}

resources/views/questions/generatedQuestions.blade.php
@extends('layouts.app')
@section('page-title', "Add Question")
@section('content')
<div id="content">
    <form action="{{route('questions.store')}}" method="POST">
        @csrf
        <input type="hidden" name="module_id" id="module_id"></input>
    <div class="question-group">`
    </div>
    <button type = "submit" class = "btn btn-purple text-white">Submit</button>
    </form>
</div>
@endsection
@section('page-level-scripts')
<script>
    window.onload = function(){
        var data = JSON.parse(localStorage.getItem('data')).results;
        console.log(data);
        var html = "";
        for(var i=0;i<data.length;i++){
            // html += data[i].question + " / " + data[i].answer;
            console.log(typeof(data[i].answer));
            var question = data[i].question;
            html += `<div>
    <div class="form-group">
        <div class="d-flex justify-content-between">
            <label for="title">Question</label>
            <div class="d-flex justify-content-between">
                
                <div class="">
                    <button type="button" id="remove-question" class="btn btn-outline-danger ml-3">Remove Question</button>
                </div>
            </div>
        </div>
        <textarea id="question"
        name="question_${i}"
            placeholder="Enter Question"
            class="form-control mt-3" row="3">
            ${question}
            </textarea>
    </div>
    <div class="form-group">
        <div class="container">
        <div class="row" id="question-${i}">
            <input type="hidden" name="" value="1" id="question-${i}-option-count">
            <div class="col-md-6">
                <div class="row" id="question-${i}-option-1">
                    <div class="col-md-1 d-flex justify-content-center align-items-center">
                        <input name="q-${i}-a" type="radio" class='correct-option' id="inlineCheckbox1 question-${i}-answer-1" value="1" checked>
                    </div>
                    <div class="col-md-10">
                        <input type="text" class="form-control options" name="q${i}[]" placeholder="Enter Option" value = "${data[i].answer}">
                    </div>
                    <div class="col-md-1 d-flex justify-content-center align-items-center">
                        <i class="fa fa-times cancel-button text-danger" id="option-1"></i>
                    </div>
                </div>
            </div>
            
        </div>
        </div>
    </div>
    <div class="form-group d-flex justify-content-end">
        <button type="button" id="add-option-${i}" class="add-option btn btn-outline-success">Add Options</button>
    </div>
    <hr>
</div>`
        }
        $(".question-group").append(html);
        // $("#content").html(html);
    }
setModuleId();
function setModuleId()
{
    // const collection = document.getElementsByClassName("module_id");
    // console.log(collection.item("0"));
    // collection.forEach(setVals); 
    // console.log() 
    $("#module_id").val(localStorage.getItem("module_id")); 
}


function addSubjects(){
    var options;

    for(var i = 0 ; i < subjects.length ; i++){
        options += `<option value="${subjects[i]["id"]}">${subjects[i]["name"]}</option>`
    }
    return options;
}

$("#add-question").click(function() {
    i++;
    $(".question-group").append(`<div>
    <div class="form-group">
        <div class="d-flex justify-content-between">
            <label for="title">Question</label>
            <div class="d-flex justify-content-between">
                <div class="form-group">
                    <select class="custom-select subject" id="test-subject">
                        <option selected value='select' >Select Subjects</option>
                    `+
                        addSubjects()
                    +`</select>
                </div>
                <div class="">
                    <button type="button" id="remove-question" class="btn btn-outline-danger ml-3">Remove Question</button>
                </div>
            </div>
        </div>
        <input type="text"
            id="question"
            name="question_${i}"
            placeholder="Enter Question"
            value = ""
            class="form-control mt-3">
    </div>
    <div class="form-group">
        <div class="container">
        <div class="row" id="question-${i}">
            <input type="hidden" name="" value="1" id="question-${i}-option-count">
            <div class="col-md-6">
                <div class="row" id="question-${i}-option-1">
                    <div class="col-md-1 d-flex justify-content-center align-items-center">
                        <input name="q-${i}-a" type="radio" class='correct-option' id="inlineCheckbox1 question-${i}-answer-1" value="1">
                    </div>
                    <div class="col-md-10">
                        <input type="text" class="form-control options" name="q${i}[]" placeholder="Enter Option" value="${data[i].answer}">
                    </div>
                    <div class="col-md-1 d-flex justify-content-center align-items-center">
                        <i class="fa fa-times cancel-button text-danger" id="option-1"></i>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="row" id="question-${i}-option-2">
                    <div class="col-md-1 d-flex justify-content-center align-items-center">
                        <input name="q-${i}-a" type="radio" class='correct-option' id="inlineCheckbox1 question-${i}-answer-2" value="2">
                    </div>
                    <div class="col-md-10">
                        <input type="text" class="form-control options" name="q${i}[]" placeholder="Enter Option">
                    </div>
                    <div class="col-md-1 d-flex justify-content-center align-items-center">
                        <i class="fa fa-times cancel-button text-danger" id="option-2"></i>
                    </div>
                </div>
            </div>
        </div>
        </div>
    </div>
    <div class="form-group d-flex justify-content-end">
        <button type="button" id="add-option-${i}" class="add-option btn btn-outline-success">Add Options</button>
    </div>
    <hr>
</div>`);


});

$(".question-group").click(function(e) {
    if (Object.values(e.target.classList).indexOf("add-option") != -1) {
        $question_id = e.target.id.substr(11);
        $data = $("#question-" + $question_id).children().length-1;
        $optionCount = $data;
        $("#question-" + $question_id).append(`<div class="col-md-6 mt-3">
        <div class="row" id="question-${$question_id}-option-${++$optionCount}">
            <div class="col-md-1 d-flex justify-content-center align-items-center">
                <input name="q-${$question_id}-a" type="radio" class='correct-option' id="inlineCheckbox1" value="${$optionCount}">
            </div>
            <div class="col-md-10">
                <input type="text" class="form-control options" name="q${$question_id}[]" placeholder="Enter Option">
            </div>
            <div class="col-md-1 d-flex justify-content-center align-items-center">
                <i class="fa fa-times cancel-button text-danger" id="option-1"></i>
            </div>
        </div>
    </div>`);
    } else if (
        Object.values(e.target.classList).indexOf("cancel-button") != -1
    ) {
        $(e.target.parentElement.parentElement.parentElement).remove();
    } else if (e.target.id === "remove-question") {
        $(
            e.target.parentElement.parentElement.parentElement.parentElement.parentElement
        ).remove();
    }
});

$("#submit-questions").click(function(e){
    errors = [];
    var questions = new Array;
    var number_of_questions = $(".question-group").children().length;
    var parent = $(".question-group").children();
    for(var i = 0 ; i < number_of_questions ; i++){
        // console.log(getQuestion(parent[i]));
        // console.log(getOptions(parent[i]));
        // console.log(getSubject(parent[i]));
        $question = getQuestion(parent[i]);
        $options = getOptions(parent[i]);
        $module = getModule(parent[i]);
        if(!hasErrors()){
            questions.push(new Array($question, $options, $module));
        }
    }
    if(hasErrors()){
        emptyStatus();
        for(var j = 0 ; j < errors.length ; j++){
             $("#status").append(`
             <div class='col-md-12'>
                 <div class='alert alert-danger alert-dismissible fade show' role='alert'>
                     ${errors[j]}
                     <button type='button' class='close' data-dismiss='alert' aria-label='Close'>
                         <span aria-hidden='true'>&times;</span>
                     </button>
                 </div>
             </div>`);
        }
        return false;
     }else{
        alert()
        errors = [];
        emptyStatus();
        console.log(questions);
        $.ajax({
            url: "http://localhost:8000/questions",
            method:"POST",
            data:{
                questions : JSON.stringify(questions),
                _token : $("input[name='_token']").val(),
            },
            success:function(result){
                console.log(result);
                if(result == "success"){
                    window.location.reload(true);
                }
            }
        });
     };
});
</script>
@endsection